Repository Instagram-Clone-Coding/Spring_instagram-clone, pull requests merged in 2021-12, with the labels that each got.

#36 Feature/follow
  src/main/java/cloneproject/Instagram/InstagramApplication.java
  src/main/java/cloneproject/Instagram/config/WebSecurityConfig.java
  src/main/java/cloneproject/Instagram/controller/FollowController.java
  src/main/java/cloneproject/Instagram/dto/error/ErrorCode.java
  src/main/java/cloneproject/Instagram/dto/result/ResultCode.java
  src/main/java/cloneproject/Instagram/exception/AlreadyFollowException.java
  src/main/java/cloneproject/Instagram/exception/CantFollowMyselfException.java
  src/main/java/cloneproject/Instagram/exception/CantUnfollowException.java
  src/main/java/cloneproject/Instagram/exception/CantUnfollowMyselfException.java
  src/main/java/cloneproject/Instagram/repository/FollowRepository.java
  src/main/java/cloneproject/Instagram/service/FollowService.java
  src/main/java/cloneproject/Instagram/util/JwtUtil.java
  src/main/java/cloneproject/Instagram/vo/FollowerInfo.java
Labels: enhancement

#40 Fix: toList() 메서드 변경
  src/main/java/cloneproject/Instagram/service/FollowService.java
Labels: bug, enhancement

#45 Feat: Swagger, JWT 만료시간 관련 설정 추가, Member 관련 업데이트
  src/main/java/cloneproject/Instagram/config/SwaggerConfig.java
  src/main/java/cloneproject/Instagram/config/WebSecurityConfig.java
  src/main/java/cloneproject/Instagram/controller/MemberController.java
  src/main/java/cloneproject/Instagram/entity/member/Member.java
  src/main/java/cloneproject/Instagram/util/JwtUtil.java
Labels: enhancement, refactor

#47 Feature/member swagger
  src/main/java/cloneproject/Instagram/config/WebSecurityConfig.java
  src/main/java/cloneproject/Instagram/controller/FollowController.java
  src/main/java/cloneproject/Instagram/controller/MemberController.java
  src/main/java/cloneproject/Instagram/dto/member/JwtDto.java
  src/main/java/cloneproject/Instagram/dto/member/LoginRequest.java
  src/main/java/cloneproject/Instagram/dto/member/RegisterRequest.java
  src/main/java/cloneproject/Instagram/dto/member/ReissueRequest.java
  src/main/java/cloneproject/Instagram/dto/member/UserProfileResponse.java
  src/main/java/cloneproject/Instagram/service/FollowService.java
  src/main/java/cloneproject/Instagram/service/JwtUserDetailsService.java
  src/main/java/cloneproject/Instagram/service/MemberService.java
Labels: enhancement
