Repository Instagram-Clone-Coding/Spring_instagram-clone, pull requests merged in 2022-02, with the labels that each got.

#80 채팅방 목록 페이징 조회 API 추가
  src/main/java/cloneproject/Instagram/controller/ChatController.java
  src/main/java/cloneproject/Instagram/dto/chat/ChatRoomCreateResponse.java
  src/main/java/cloneproject/Instagram/dto/chat/JoinRoomDTO.java
  src/main/java/cloneproject/Instagram/dto/chat/MemberSimpleInfo.java
  src/main/java/cloneproject/Instagram/dto/chat/MessageDTO.java
  src/main/java/cloneproject/Instagram/entity/chat/JoinRoom.java
  src/main/java/cloneproject/Instagram/entity/chat/Room.java
  src/main/java/cloneproject/Instagram/repository/chat/JoinRoomRepositoryQuerydslImpl.java
  src/main/java/cloneproject/Instagram/repository/chat/RoomMemberRepository.java
  src/main/java/cloneproject/Instagram/service/ChatService.java
Labels: enhancement

#82 WebSocket 설정, 채팅 메시지 전송 기능 추가
  src/main/java/cloneproject/Instagram/config/WebSocketConfig.java
  src/main/java/cloneproject/Instagram/controller/ChatController.java
  src/main/java/cloneproject/Instagram/dto/chat/MessageDTO.java
  src/main/java/cloneproject/Instagram/dto/chat/MessageRequest.java
  src/main/java/cloneproject/Instagram/entity/chat/JoinRoom.java
  src/main/java/cloneproject/Instagram/repository/chat/RoomMemberRepository.java
  src/main/java/cloneproject/Instagram/service/ChatService.java
Labels: enhancement

#86 채팅 API 추가 및 로직 추가
  src/main/java/cloneproject/Instagram/controller/ChatController.java
  src/main/java/cloneproject/Instagram/dto/MessageResponse.java
  src/main/java/cloneproject/Instagram/dto/chat/IndicateDTO.java
  src/main/java/cloneproject/Instagram/dto/chat/IndicateRequest.java
  src/main/java/cloneproject/Instagram/dto/chat/JoinRoomDTO.java
  src/main/java/cloneproject/Instagram/dto/chat/MessageAction.java
  src/main/java/cloneproject/Instagram/dto/chat/MessageDTO.java
  src/main/java/cloneproject/Instagram/dto/chat/MessageResponse.java
  src/main/java/cloneproject/Instagram/dto/chat/MessageSeenDTO.java
  src/main/java/cloneproject/Instagram/entity/chat/Room.java
  src/main/java/cloneproject/Instagram/repository/chat/JoinRoomRepository.java
  src/main/java/cloneproject/Instagram/repository/chat/JoinRoomRepositoryQuerydslImpl.java
  src/main/java/cloneproject/Instagram/service/ChatService.java
Labels: enhancement

#88 채팅방 메시지 목록 페이징 조회 API 추가
  src/main/java/cloneproject/Instagram/controller/ChatController.java
  src/main/java/cloneproject/Instagram/dto/chat/MessageDTO.java
  src/main/java/cloneproject/Instagram/dto/result/ResultCode.java
  src/main/java/cloneproject/Instagram/repository/chat/JoinRoomRepositoryQuerydslImpl.java
  src/main/java/cloneproject/Instagram/repository/chat/MessageRepository.java
  src/main/java/cloneproject/Instagram/repository/chat/MessageRepositoryQuerydsl.java
  src/main/java/cloneproject/Instagram/repository/chat/MessageRepositoryQuerydslImpl.java
  src/main/java/cloneproject/Instagram/service/ChatService.java
Labels: enhancement

#93 댓글 작성/삭제/조회 API 추가
  src/main/java/cloneproject/Instagram/config/WebSecurityConfig.java
  src/main/java/cloneproject/Instagram/controller/PostController.java
  src/main/java/cloneproject/Instagram/dto/comment/CommentCreateRequest.java
  src/main/java/cloneproject/Instagram/dto/comment/CommentCreateResponse.java
  src/main/java/cloneproject/Instagram/dto/comment/CommentDTO.java
  src/main/java/cloneproject/Instagram/dto/error/ErrorCode.java
  src/main/java/cloneproject/Instagram/dto/member/MenuMemberDTO.java
  src/main/java/cloneproject/Instagram/dto/result/ResultCode.java
  src/main/java/cloneproject/Instagram/exception/CommentCantDeleteException.java
  src/main/java/cloneproject/Instagram/exception/CommentNotFoundException.java
  src/main/java/cloneproject/Instagram/repository/chat/JoinRoomRepository.java
  src/main/java/cloneproject/Instagram/repository/post/CommentRepository.java
  src/main/java/cloneproject/Instagram/repository/post/CommentRepositoryQuerydsl.java
  src/main/java/cloneproject/Instagram/repository/post/CommentRepositoryQuerydslImpl.java
  src/main/java/cloneproject/Instagram/repository/post/PostRepositoryQuerydslImpl.java
  src/main/java/cloneproject/Instagram/service/PostService.java
Labels: enhancement

#94 MemberService 테스트 작성
  src/main/java/cloneproject/Instagram/controller/MemberAuthController.java
  src/main/java/cloneproject/Instagram/dto/error/ErrorCode.java
  src/test/java/cloneproject/Instagram/WithMockCustomUser.java
  src/test/java/cloneproject/Instagram/WithMockCustomUserSecurityContextFactory.java
  src/test/java/cloneproject/Instagram/repository/MemberRepositoryTest.java
  src/test/java/cloneproject/Instagram/service/MemberServiceTest.java
Labels: test

#96 Fix: JoinRoom 중복 체크 로직 정상화
  src/main/java/cloneproject/Instagram/service/ChatService.java
Labels: bug

#98 채팅방 메시지 전송 API 로직 수정 등
  src/main/java/cloneproject/Instagram/controller/ChatController.java
  src/main/java/cloneproject/Instagram/entity/chat/Message.java
  src/main/java/cloneproject/Instagram/repository/chat/JoinRoomRepositoryQuerydsl.java
  src/main/java/cloneproject/Instagram/repository/chat/JoinRoomRepositoryQuerydslImpl.java
  src/main/java/cloneproject/Instagram/service/ChatService.java
Labels: bug, enhancement

#99 MemberRepository 테스트
  build.gradle
  src/main/java/cloneproject/Instagram/controller/MemberAuthController.java
  src/main/java/cloneproject/Instagram/dto/error/ErrorCode.java
  src/main/java/cloneproject/Instagram/dto/member/FollowerDTO.java
  src/main/java/cloneproject/Instagram/dto/member/MiniProfileResponse.java
  src/main/java/cloneproject/Instagram/dto/post/MiniProfilePostDTO.java
  src/main/java/cloneproject/Instagram/exception/NoConfirmEmailException.java
  src/main/java/cloneproject/Instagram/repository/MemberRepositoryQuerydsl.java
  src/main/java/cloneproject/Instagram/repository/MemberRepositoryQuerydslImpl.java
  src/main/java/cloneproject/Instagram/service/BlockService.java
  src/main/java/cloneproject/Instagram/service/EmailCodeService.java
  src/main/java/cloneproject/Instagram/service/MemberAuthService.java
  src/test/java/cloneproject/Instagram/repository/MemberRepositoryTest.java
  src/test/java/cloneproject/Instagram/service/MemberServiceTest.java
Labels: refactor, test

#101 게시물 목록 조회 API, 채팅방 생성 API, 채팅방 목록 조회 API 응답 데이터 추가
  src/main/java/cloneproject/Instagram/dto/chat/ChatRoomCreateResponse.java
  src/main/java/cloneproject/Instagram/dto/chat/JoinRoomDTO.java
  src/main/java/cloneproject/Instagram/dto/comment/CommentDTO.java
  src/main/java/cloneproject/Instagram/dto/post/PostDTO.java
  src/main/java/cloneproject/Instagram/entity/comment/RecentComment.java
  src/main/java/cloneproject/Instagram/repository/chat/JoinRoomRepositoryQuerydslImpl.java
  src/main/java/cloneproject/Instagram/repository/post/PostRepositoryQuerydslImpl.java
  src/main/java/cloneproject/Instagram/repository/post/RecentCommentRepository.java
  src/main/java/cloneproject/Instagram/service/ChatService.java
  src/main/java/cloneproject/Instagram/service/PostService.java
Labels: enhancement

#103 Follow, Block, MemberPost 테스트 작성
  src/test/java/cloneproject/Instagram/repository/FollowRepositoryTest.java
  src/test/java/cloneproject/Instagram/repository/MemberPostRepositoryTest.java
  src/test/java/cloneproject/Instagram/repository/MemberRepositoryTest.java
  src/test/java/cloneproject/Instagram/service/BlockServiceTest.java
  src/test/java/cloneproject/Instagram/service/FollowServiceTest.java
Labels: test

#107 좋아요, 알림, 멘션 관련 API 업데이트 및 채팅 API 에러 해결
  src/main/java/cloneproject/Instagram/controller/AlarmController.java
  src/main/java/cloneproject/Instagram/controller/PostController.java
  src/main/java/cloneproject/Instagram/dto/alarm/AlarmContentDTO.java
  src/main/java/cloneproject/Instagram/dto/alarm/AlarmDTO.java
  src/main/java/cloneproject/Instagram/dto/alarm/AlarmFollowDTO.java
  src/main/java/cloneproject/Instagram/dto/alarm/AlarmType.java
  src/main/java/cloneproject/Instagram/dto/error/ErrorCode.java
  src/main/java/cloneproject/Instagram/dto/member/LikeMembersDTO.java
  src/main/java/cloneproject/Instagram/dto/result/ResultCode.java
  src/main/java/cloneproject/Instagram/entity/alarms/Alarm.java
  src/main/java/cloneproject/Instagram/entity/member/MemberStory.java
  src/main/java/cloneproject/Instagram/entity/mention/Mention.java
  src/main/java/cloneproject/Instagram/entity/mention/MentionType.java
  src/main/java/cloneproject/Instagram/entity/post/Post.java
  src/main/java/cloneproject/Instagram/exception/CommentLikeAlreadyExistException.java
  src/main/java/cloneproject/Instagram/exception/CommentLikeNotFoundException.java
  src/main/java/cloneproject/Instagram/exception/MismatchedAlarmTypeException.java
  src/main/java/cloneproject/Instagram/repository/AlarmRepository.java
  src/main/java/cloneproject/Instagram/repository/AlarmRepositoryJdbc.java
  src/main/java/cloneproject/Instagram/repository/AlarmRepositoryJdbcImpl.java
  src/main/java/cloneproject/Instagram/repository/AlarmRepositoryQuerydsl.java
  src/main/java/cloneproject/Instagram/repository/AlarmRepositoryQuerydslImpl.java
  src/main/java/cloneproject/Instagram/repository/BookmarkRepository.java
  src/main/java/cloneproject/Instagram/repository/CommentLikeRepository.java
  src/main/java/cloneproject/Instagram/repository/MemberPostRepositoryQuerydslImpl.java
  src/main/java/cloneproject/Instagram/repository/MemberRepository.java
  src/main/java/cloneproject/Instagram/repository/MemberRepositoryQuerydslImpl.java
  src/main/java/cloneproject/Instagram/repository/MentionRepository.java
  src/main/java/cloneproject/Instagram/repository/MentionRepositoryJdbc.java
  src/main/java/cloneproject/Instagram/repository/MentionRepositoryJdbcImpl.java
  src/main/java/cloneproject/Instagram/repository/PostImageRepository.java
  src/main/java/cloneproject/Instagram/repository/PostLikeRepository.java
  src/main/java/cloneproject/Instagram/repository/PostLikeRepositoryQuerydsl.java
  src/main/java/cloneproject/Instagram/repository/PostLikeRepositoryQuerydslImpl.java
  src/main/java/cloneproject/Instagram/repository/PostTagRepository.java
  src/main/java/cloneproject/Instagram/repository/chat/JoinRoomRepositoryQuerydslImpl.java
  src/main/java/cloneproject/Instagram/repository/chat/MessageRepositoryQuerydslImpl.java
  src/main/java/cloneproject/Instagram/repository/post/CommentRepository.java
  src/main/java/cloneproject/Instagram/repository/post/CommentRepositoryQuerydslImpl.java
  src/main/java/cloneproject/Instagram/repository/post/PostRepository.java
  src/main/java/cloneproject/Instagram/repository/post/RecentCommentRepository.java
  src/main/java/cloneproject/Instagram/service/AlarmService.java
  src/main/java/cloneproject/Instagram/service/FollowService.java
  src/main/java/cloneproject/Instagram/service/MemberService.java
  src/main/java/cloneproject/Instagram/service/PostService.java
  src/main/java/cloneproject/Instagram/util/S3Uploader.java
  src/main/java/cloneproject/Instagram/util/StringExtractUtil.java
Labels: bug, enhancement

#108 Test/member controller
  src/main/java/cloneproject/Instagram/advice/GlobalExceptionHandler.java
  src/main/java/cloneproject/Instagram/controller/MemberAuthController.java
  src/main/java/cloneproject/Instagram/controller/MemberController.java
  src/main/java/cloneproject/Instagram/dto/error/ErrorResponse.java
  src/main/java/cloneproject/Instagram/dto/member/EditProfileRequest.java
  src/test/java/cloneproject/Instagram/controller/MemberAuthControllerTest.java
  src/test/java/cloneproject/Instagram/controller/MemberControllerTest.java
Labels: enhancement, test

#110 DM 단톡 기능 추가 및 알람 목록 페이징 조회 API 쿼리 수정
  src/main/java/cloneproject/Instagram/controller/ChatController.java
  src/main/java/cloneproject/Instagram/dto/result/ResultCode.java
  src/main/java/cloneproject/Instagram/repository/AlarmRepositoryQuerydslImpl.java
  src/main/java/cloneproject/Instagram/service/ChatService.java
Labels: enhancement, refactor

#113 게시물 이미지 태그 -> 알림이 아닌 DM으로 게시물 공유하는 방식으로 변경 등
  src/main/java/cloneproject/Instagram/dto/chat/JoinRoomDTO.java
  src/main/java/cloneproject/Instagram/dto/chat/MessageDTO.java
  src/main/java/cloneproject/Instagram/dto/chat/MessageRequest.java
  src/main/java/cloneproject/Instagram/entity/chat/Message.java
  src/main/java/cloneproject/Instagram/entity/chat/MessageImage.java
  src/main/java/cloneproject/Instagram/entity/chat/MessagePost.java
  src/main/java/cloneproject/Instagram/entity/chat/MessageText.java
  src/main/java/cloneproject/Instagram/entity/chat/MessageType.java
  src/main/java/cloneproject/Instagram/entity/chat/Room.java
  src/main/java/cloneproject/Instagram/entity/member/Block.java
  src/main/java/cloneproject/Instagram/entity/member/Follow.java
  src/main/java/cloneproject/Instagram/entity/member/Member.java
  src/main/java/cloneproject/Instagram/repository/MemberRepository.java
  src/main/java/cloneproject/Instagram/repository/chat/JoinRomRepositoryJdbc.java
  src/main/java/cloneproject/Instagram/repository/chat/JoinRomRepositoryJdbcImpl.java
  src/main/java/cloneproject/Instagram/repository/chat/JoinRoomRepository.java
  src/main/java/cloneproject/Instagram/repository/chat/JoinRoomRepositoryQuerydslImpl.java
  src/main/java/cloneproject/Instagram/repository/chat/MessagePostRepository.java
  src/main/java/cloneproject/Instagram/repository/chat/MessageRepositoryQuerydslImpl.java
  src/main/java/cloneproject/Instagram/repository/chat/MessageTextRepository.java
  src/main/java/cloneproject/Instagram/repository/chat/RoomMemberRepository.java
  src/main/java/cloneproject/Instagram/repository/chat/RoomMemberRepositoryJdbc.java
  src/main/java/cloneproject/Instagram/repository/chat/RoomMemberRepositoryJdbcImpl.java
  src/main/java/cloneproject/Instagram/repository/chat/RoomUnreadMemberRepository.java
  src/main/java/cloneproject/Instagram/repository/chat/RoomUnreadMemberRepositoryJdbc.java
  src/main/java/cloneproject/Instagram/repository/chat/RoomUnreadMemberRepositoryJdbcImpl.java
  src/main/java/cloneproject/Instagram/service/ChatService.java
  src/main/java/cloneproject/Instagram/service/PostService.java
Labels: enhancement, refactor

#115 채팅 API 추가 및 변경
  src/main/java/cloneproject/Instagram/controller/ChatController.java
  src/main/java/cloneproject/Instagram/dto/chat/MessageAction.java
  src/main/java/cloneproject/Instagram/dto/chat/MessageDTO.java
  src/main/java/cloneproject/Instagram/dto/chat/MessageSimpleDTO.java
  src/main/java/cloneproject/Instagram/dto/error/ErrorCode.java
  src/main/java/cloneproject/Instagram/entity/chat/JoinRoom.java
  src/main/java/cloneproject/Instagram/entity/chat/Message.java
  src/main/java/cloneproject/Instagram/entity/chat/Room.java
  src/main/java/cloneproject/Instagram/entity/chat/RoomUnreadMember.java
  src/main/java/cloneproject/Instagram/exception/InvalidInputException.java
  src/main/java/cloneproject/Instagram/exception/MessageLikeAlreadyExistException.java
  src/main/java/cloneproject/Instagram/exception/MessageLikeNotFoundException.java
  src/main/java/cloneproject/Instagram/exception/MessageNotFoundException.java
  src/main/java/cloneproject/Instagram/repository/chat/JoinRomRepositoryJdbc.java
  src/main/java/cloneproject/Instagram/repository/chat/JoinRomRepositoryJdbcImpl.java
  src/main/java/cloneproject/Instagram/repository/chat/JoinRoomRepository.java
  src/main/java/cloneproject/Instagram/repository/chat/JoinRoomRepositoryQuerydslImpl.java
  src/main/java/cloneproject/Instagram/repository/chat/MessageLikeRepository.java
  src/main/java/cloneproject/Instagram/repository/chat/MessageRepository.java
  src/main/java/cloneproject/Instagram/repository/chat/MessageRepositoryQuerydslImpl.java
  src/main/java/cloneproject/Instagram/repository/chat/RoomMemberRepository.java
  src/main/java/cloneproject/Instagram/repository/chat/RoomUnreadMemberRepository.java
  src/main/java/cloneproject/Instagram/repository/chat/RoomUnreadMemberRepositoryJdbc.java
  src/main/java/cloneproject/Instagram/repository/chat/RoomUnreadMemberRepositoryJdbcImpl.java
  src/main/java/cloneproject/Instagram/service/ChatService.java
  src/main/java/cloneproject/Instagram/service/PostService.java
Labels: enhancement, refactor
