Repository Instagram-Clone-Coding/Spring_instagram-clone, pull requests merged in 2022-01, with the labels that each got.

#56 Refactor/aws
  build.gradle
  src/main/java/cloneproject/Instagram/config/AWSConfig.java
  src/main/java/cloneproject/Instagram/dto/error/ErrorCode.java
  src/main/java/cloneproject/Instagram/entity/member/Member.java
  src/main/java/cloneproject/Instagram/exception/CantConvertFileException.java
  src/main/java/cloneproject/Instagram/exception/UploadProfileImageFailException.java
  src/main/java/cloneproject/Instagram/service/MemberService.java
  src/main/java/cloneproject/Instagram/util/ImageUtil.java
  src/main/java/cloneproject/Instagram/util/S3Uploader.java
  src/main/java/cloneproject/Instagram/vo/Image.java
Labels: refactor

#50 게시물 목록 조회 API 추가
  src/main/java/cloneproject/Instagram/controller/PostController.java
  src/main/java/cloneproject/Instagram/dto/error/ErrorCode.java
  src/main/java/cloneproject/Instagram/dto/post/PostDTO.java
  src/main/java/cloneproject/Instagram/dto/post/PostImageDTO.java
  src/main/java/cloneproject/Instagram/dto/post/PostTagDTO.java
  src/main/java/cloneproject/Instagram/dto/result/ResultCode.java
  src/main/java/cloneproject/Instagram/entity/post/Post.java
  src/main/java/cloneproject/Instagram/entity/post/PostImage.java
  src/main/java/cloneproject/Instagram/entity/post/PostTag.java
  src/main/java/cloneproject/Instagram/exception/InvalidTagLocationException.java
  src/main/java/cloneproject/Instagram/repository/PostRepository.java
  src/main/java/cloneproject/Instagram/repository/PostRepositoryCustom.java
  src/main/java/cloneproject/Instagram/repository/PostRepositoryCustomImpl.java
  src/main/java/cloneproject/Instagram/service/PostService.java
  src/main/java/cloneproject/Instagram/vo/Tag.java
Labels: enhancement

#58 AWS S3 업로드 시 발생하는 에러 해결
  src/main/java/cloneproject/Instagram/service/PostService.java
  src/main/java/cloneproject/Instagram/util/ImageUtil.java
Labels: bug, refactor

#61 게시물 목록 조회 API 분할, 게시물 조회 API 추가 및 쿼리 최적화
  src/main/java/cloneproject/Instagram/controller/PostController.java
  src/main/java/cloneproject/Instagram/dto/comment/CommentDTO.java
  src/main/java/cloneproject/Instagram/dto/post/PostImageDTO.java
  src/main/java/cloneproject/Instagram/dto/post/PostResponse.java
  src/main/java/cloneproject/Instagram/dto/post/PostTagDTO.java
  src/main/java/cloneproject/Instagram/dto/result/ResultCode.java
  src/main/java/cloneproject/Instagram/entity/comment/Comment.java
  src/main/java/cloneproject/Instagram/repository/PostRepositoryCustom.java
  src/main/java/cloneproject/Instagram/repository/PostRepositoryCustomImpl.java
  src/main/java/cloneproject/Instagram/service/PostService.java
Labels: enhancement, refactor

#63 게시물 업로드 API 개선 및 쿼리 최적화
  src/main/java/cloneproject/Instagram/advice/GlobalExceptionHandler.java
  src/main/java/cloneproject/Instagram/controller/PostController.java
  src/main/java/cloneproject/Instagram/dto/error/ErrorCode.java
  src/main/java/cloneproject/Instagram/dto/error/ErrorResponse.java
  src/main/java/cloneproject/Instagram/dto/post/PostImageTagDTO.java
  src/main/java/cloneproject/Instagram/dto/post/PostImageTagRequest.java
  src/main/java/cloneproject/Instagram/dto/post/PostImageUploadRequest.java
  src/main/java/cloneproject/Instagram/dto/post/PostImageUploadResponse.java
  src/main/java/cloneproject/Instagram/dto/post/PostUploadRequest.java
  src/main/java/cloneproject/Instagram/exception/BusinessException.java
  src/main/java/cloneproject/Instagram/exception/InvalidTagLocationException.java
  src/main/java/cloneproject/Instagram/exception/PostImageInvalidException.java
  src/main/java/cloneproject/Instagram/exception/PostImageTagInvalidException.java
  src/main/java/cloneproject/Instagram/repository/PostImageRepository.java
  src/main/java/cloneproject/Instagram/repository/PostRepository.java
  src/main/java/cloneproject/Instagram/repository/PostRepositoryJdbc.java
  src/main/java/cloneproject/Instagram/repository/PostRepositoryJdbcImpl.java
  src/main/java/cloneproject/Instagram/repository/PostRepositoryQuerydsl.java
  src/main/java/cloneproject/Instagram/repository/PostRepositoryQuerydslImpl.java
  src/main/java/cloneproject/Instagram/service/PostService.java
Labels: refactor

#64 Feature/search member
  build.gradle
  src/main/java/cloneproject/Instagram/config/EmbeddedRedisConfig.java
  src/main/java/cloneproject/Instagram/config/JwtFilter.java
  src/main/java/cloneproject/Instagram/config/RedisRepositoryConfig.java
  src/main/java/cloneproject/Instagram/config/WebSecurityConfig.java
  src/main/java/cloneproject/Instagram/controller/MemberController.java
  src/main/java/cloneproject/Instagram/dto/error/ErrorCode.java
  src/main/java/cloneproject/Instagram/dto/member/EditProfileRequest.java
  src/main/java/cloneproject/Instagram/dto/member/JwtDto.java
  src/main/java/cloneproject/Instagram/dto/member/MiniProfileResponse.java
  src/main/java/cloneproject/Instagram/dto/member/RegisterRequest.java
  src/main/java/cloneproject/Instagram/dto/member/UserProfileResponse.java
  src/main/java/cloneproject/Instagram/dto/result/ResultCode.java
  src/main/java/cloneproject/Instagram/entity/member/Member.java
  src/main/java/cloneproject/Instagram/entity/redis/EmailCode.java
  src/main/java/cloneproject/Instagram/repository/EmailCodeRedisRepository.java
  src/main/java/cloneproject/Instagram/repository/MemberRepository.java
  src/main/java/cloneproject/Instagram/repository/specs/MemberSpecification.java
  src/main/java/cloneproject/Instagram/service/EmailCodeService.java
  src/main/java/cloneproject/Instagram/service/EmailService.java
  src/main/java/cloneproject/Instagram/service/FollowService.java
  src/main/java/cloneproject/Instagram/service/MemberService.java
  src/main/java/cloneproject/Instagram/util/DateUtil.java
  src/main/java/cloneproject/Instagram/util/JwtUtil.java
  src/main/java/cloneproject/Instagram/util/RedisUtil.java
  src/main/java/cloneproject/Instagram/vo/SearchedMemberInfo.java
Labels: enhancement

#66 게시물 좋아요/취소, 저장/취소 API 추가
  src/main/java/cloneproject/Instagram/controller/PostController.java
  src/main/java/cloneproject/Instagram/dto/StatusResponse.java
  src/main/java/cloneproject/Instagram/dto/error/ErrorCode.java
  src/main/java/cloneproject/Instagram/dto/result/ResultCode.java
  src/main/java/cloneproject/Instagram/exception/BookmarkAlreadyExistException.java
  src/main/java/cloneproject/Instagram/exception/BookmarkNotFoundException.java
  src/main/java/cloneproject/Instagram/exception/PostLikeAlreadyExistException.java
  src/main/java/cloneproject/Instagram/exception/PostLikeNotFoundException.java
  src/main/java/cloneproject/Instagram/repository/BookmarkRepository.java
  src/main/java/cloneproject/Instagram/repository/PostLikeRepository.java
  src/main/java/cloneproject/Instagram/repository/post/PostRepository.java
  src/main/java/cloneproject/Instagram/repository/post/PostRepositoryJdbc.java
  src/main/java/cloneproject/Instagram/repository/post/PostRepositoryJdbcImpl.java
  src/main/java/cloneproject/Instagram/repository/post/PostRepositoryQuerydsl.java
  src/main/java/cloneproject/Instagram/repository/post/PostRepositoryQuerydslImpl.java
  src/main/java/cloneproject/Instagram/service/PostService.java
Labels: enhancement

#71 멤버관련 API 쿼리 개선, 차단 기능 활성화
  src/main/java/cloneproject/Instagram/controller/FollowController.java
  src/main/java/cloneproject/Instagram/controller/MemberController.java
  src/main/java/cloneproject/Instagram/controller/MemberPostController.java
  src/main/java/cloneproject/Instagram/dto/member/FollowDTO.java
  src/main/java/cloneproject/Instagram/dto/member/FollowerDTO.java
  src/main/java/cloneproject/Instagram/dto/member/MenuMemberDTO.java
  src/main/java/cloneproject/Instagram/dto/member/MiniProfileResponse.java
  src/main/java/cloneproject/Instagram/dto/member/SearchedMemberDTO.java
  src/main/java/cloneproject/Instagram/dto/member/UserProfileResponse.java
  src/main/java/cloneproject/Instagram/dto/post/MemberPostDTO.java
  src/main/java/cloneproject/Instagram/dto/post/MiniProfilePostDTO.java
  src/main/java/cloneproject/Instagram/dto/result/ResultCode.java
  src/main/java/cloneproject/Instagram/repository/BlockRepository.java
  src/main/java/cloneproject/Instagram/repository/FollowRepository.java
  src/main/java/cloneproject/Instagram/repository/FollowRepositoryQuerydsl.java
  src/main/java/cloneproject/Instagram/repository/FollowRepositoryQuerydslImpl.java
  src/main/java/cloneproject/Instagram/repository/MemberRepository.java
  src/main/java/cloneproject/Instagram/repository/MemberRepositoryQuerydsl.java
  src/main/java/cloneproject/Instagram/repository/MemberRepositoryQuerydslImpl.java
  src/main/java/cloneproject/Instagram/service/BlockService.java
  src/main/java/cloneproject/Instagram/service/FollowService.java
  src/main/java/cloneproject/Instagram/service/MemberAuthService.java
  src/main/java/cloneproject/Instagram/service/MemberPostService.java
  src/main/java/cloneproject/Instagram/service/MemberService.java
  src/main/java/cloneproject/Instagram/util/AuthUtil.java
  src/main/java/cloneproject/Instagram/util/PostUtil.java
  src/main/java/cloneproject/Instagram/vo/FollowerInfo.java
  src/main/java/cloneproject/Instagram/vo/SearchedMemberInfo.java
Labels: enhancement, refactor

#72 게시물 조회 쿼리 오류 해결
  src/main/java/cloneproject/Instagram/dto/post/PostDTO.java
  src/main/java/cloneproject/Instagram/dto/post/PostLikeDTO.java
  src/main/java/cloneproject/Instagram/dto/post/PostResponse.java
  src/main/java/cloneproject/Instagram/repository/post/PostRepositoryQuerydslImpl.java
Labels: bug

#75 알림 API 구현
  src/main/java/cloneproject/Instagram/controller/AlarmController.java
  src/main/java/cloneproject/Instagram/dto/alarm/AlarmDTO.java
  src/main/java/cloneproject/Instagram/dto/alarm/AlarmType.java
  src/main/java/cloneproject/Instagram/dto/result/ResultCode.java
  src/main/java/cloneproject/Instagram/entity/alarms/Alarm.java
  src/main/java/cloneproject/Instagram/repository/AlarmRepository.java
  src/main/java/cloneproject/Instagram/repository/AlarmRepositoryQuerydsl.java
  src/main/java/cloneproject/Instagram/repository/AlarmRepositoryQuerydslImpl.java
  src/main/java/cloneproject/Instagram/repository/MemberRepositoryQuerydsl.java
  src/main/java/cloneproject/Instagram/repository/MemberRepositoryQuerydslImpl.java
  src/main/java/cloneproject/Instagram/service/AlarmService.java
  src/main/java/cloneproject/Instagram/service/FollowService.java
  src/main/java/cloneproject/Instagram/service/PostService.java
  src/main/java/cloneproject/Instagram/util/S3Uploader.java
Labels: enhancement, refactor

#78 DM 관련 엔티티, 채팅방 생성, 조회, 삭제 API 추가
  src/main/java/cloneproject/Instagram/controller/ChatController.java
  src/main/java/cloneproject/Instagram/dto/chat/ChatRoomCreateResponse.java
  src/main/java/cloneproject/Instagram/dto/chat/ChatRoomInquireResponse.java
  src/main/java/cloneproject/Instagram/dto/chat/JoinRoomDTO.java
  src/main/java/cloneproject/Instagram/dto/chat/JoinRoomDeleteResponse.java
  src/main/java/cloneproject/Instagram/dto/chat/MessageDTO.java
  src/main/java/cloneproject/Instagram/dto/chat/Opponent.java
  src/main/java/cloneproject/Instagram/dto/error/ErrorCode.java
  src/main/java/cloneproject/Instagram/dto/result/ResultCode.java
  src/main/java/cloneproject/Instagram/entity/chat/JoinRoom.java
  src/main/java/cloneproject/Instagram/entity/chat/Message.java
  src/main/java/cloneproject/Instagram/entity/chat/MessageImage.java
  src/main/java/cloneproject/Instagram/entity/chat/MessageLike.java
  src/main/java/cloneproject/Instagram/entity/chat/MessageType.java
  src/main/java/cloneproject/Instagram/entity/chat/Room.java
  src/main/java/cloneproject/Instagram/entity/chat/RoomMember.java
  src/main/java/cloneproject/Instagram/entity/chat/RoomUnreadMember.java
  src/main/java/cloneproject/Instagram/exception/ChatRoomNotFoundException.java
  src/main/java/cloneproject/Instagram/exception/JoinRoomNotFoundException.java
  src/main/java/cloneproject/Instagram/repository/chat/JoinRoomRepository.java
  src/main/java/cloneproject/Instagram/repository/chat/JoinRoomRepositoryQuerydsl.java
  src/main/java/cloneproject/Instagram/repository/chat/JoinRoomRepositoryQuerydslImpl.java
  src/main/java/cloneproject/Instagram/repository/chat/MessageImageRepository.java
  src/main/java/cloneproject/Instagram/repository/chat/MessageLikeRepository.java
  src/main/java/cloneproject/Instagram/repository/chat/MessageRepository.java
  src/main/java/cloneproject/Instagram/repository/chat/RoomMemberRepository.java
  src/main/java/cloneproject/Instagram/repository/chat/RoomRepository.java
  src/main/java/cloneproject/Instagram/repository/chat/RoomUnreadMemberRepository.java
  src/main/java/cloneproject/Instagram/service/ChatService.java
Labels: enhancement

#79 유저 저장한, 태그된 게시물 조회 API
  src/main/java/cloneproject/Instagram/config/WebSecurityConfig.java
  src/main/java/cloneproject/Instagram/controller/BlockController.java
  src/main/java/cloneproject/Instagram/controller/FollowController.java
  src/main/java/cloneproject/Instagram/controller/MemberPostController.java
  src/main/java/cloneproject/Instagram/dto/result/ResultCode.java
  src/main/java/cloneproject/Instagram/repository/MemberPostRepositoryQuerydsl.java
  src/main/java/cloneproject/Instagram/repository/MemberPostRepositoryQuerydslImpl.java
  src/main/java/cloneproject/Instagram/repository/MemberRepository.java
  src/main/java/cloneproject/Instagram/repository/MemberRepositoryQuerydsl.java
  src/main/java/cloneproject/Instagram/repository/MemberRepositoryQuerydslImpl.java
  src/main/java/cloneproject/Instagram/service/MemberPostService.java
Labels: enhancement
