Repository Instagram-Clone-Coding/Spring_instagram-clone, pull requests merged in 2022-09, with the labels that each got.

#210 해시태그 프로필 조회 API 구현
  src/main/java/cloneproject/Instagram/domain/feed/service/PostService.java
  src/main/java/cloneproject/Instagram/domain/hashtag/controller/HashtagController.java
  src/main/java/cloneproject/Instagram/domain/hashtag/dto/HashtagProfileResponse.java
  src/main/java/cloneproject/Instagram/domain/hashtag/repository/HashtagPostRepository.java
  src/main/java/cloneproject/Instagram/domain/hashtag/repository/querydsl/HashtagPostRepositoryQuerydsl.java
  src/main/java/cloneproject/Instagram/domain/hashtag/repository/querydsl/HashtagPostRepositoryQuerydslImpl.java
  src/main/java/cloneproject/Instagram/domain/hashtag/service/HashtagService.java
  src/main/java/cloneproject/Instagram/global/result/ResultCode.java
Labels: ✈enhancement

#211 BlockRepository 테스트 작성
  src/test/java/cloneproject/Instagram/domain/member/repository/BlockRepositoryTest.java
  src/test/java/cloneproject/Instagram/domain/member/repository/querydsl/BlockRepositoryQuerydslTest.java
Labels: 🔍test

#213 멤버 도메인 Redis Repository 테스트 작성
  src/main/java/cloneproject/Instagram/domain/member/entity/redis/RegisterCode.java
  src/main/java/cloneproject/Instagram/domain/member/repository/redis/EmailCodeRedisRepository.java
  src/main/java/cloneproject/Instagram/domain/member/repository/redis/RefreshTokenRedisRepository.java
  src/main/java/cloneproject/Instagram/domain/member/repository/redis/RegisterCodeRedisRepository.java
  src/main/java/cloneproject/Instagram/domain/member/repository/redis/ResetPasswordCodeRedisRepository.java
  src/main/java/cloneproject/Instagram/domain/member/service/EmailCodeService.java
  src/main/java/cloneproject/Instagram/domain/member/service/MemberAuthService.java
  src/main/java/cloneproject/Instagram/domain/member/service/RefreshTokenService.java
  src/main/java/cloneproject/Instagram/infra/location/dto/Location.java
  src/test/java/cloneproject/Instagram/domain/member/repository/redis/RefreshTokenRedisRepositoryTest.java
  src/test/java/cloneproject/Instagram/domain/member/repository/redis/RegisterCodeRedisRepositoryTest.java
  src/test/java/cloneproject/Instagram/domain/member/repository/redis/ResetPasswordCodeRedisRepositoryTest.java
  src/test/java/cloneproject/Instagram/util/LocationUtils.java
  src/test/java/cloneproject/Instagram/util/domain/member/redis/RefreshTokenUtils.java
  src/test/java/cloneproject/Instagram/util/domain/member/redis/RegisterCodeUtils.java
  src/test/java/cloneproject/Instagram/util/domain/member/redis/ResetPasswordCodeUtils.java
Labels: 🔍test

#218 BlockService 리팩토링 및 테스트 작성
  src/main/java/cloneproject/Instagram/domain/member/exception/AlreadyBlockException.java
  src/main/java/cloneproject/Instagram/domain/member/exception/BlockMyselfFailException.java
  src/main/java/cloneproject/Instagram/domain/member/exception/UnblockFailException.java
  src/main/java/cloneproject/Instagram/domain/member/exception/UnblockMyselfFailException.java
  src/main/java/cloneproject/Instagram/domain/member/service/BlockService.java
  src/main/java/cloneproject/Instagram/global/error/ErrorCode.java
  src/test/java/cloneproject/Instagram/domain/member/repository/MemberRepositoryTest.java
  src/test/java/cloneproject/Instagram/domain/member/repository/redis/RegisterCodeRedisRepositoryTest.java
  src/test/java/cloneproject/Instagram/domain/member/repository/redis/ResetPasswordCodeRedisRepositoryTest.java
  src/test/java/cloneproject/Instagram/domain/member/service/BlockServiceTest.java
  src/test/java/cloneproject/Instagram/util/domain/member/MemberUtils.java
Labels: 💎refactor, 🔍test

#219 팔로우 하려는 대상이 날 차단한 경우 수정
  src/main/java/cloneproject/Instagram/domain/follow/controller/FollowController.java
  src/main/java/cloneproject/Instagram/domain/follow/service/FollowService.java
  src/main/java/cloneproject/Instagram/global/result/ResultCode.java
Labels: 💎refactor

#224 Feed 도메인 리팩토링, 기능 추가 및 수정
  .gitignore
  src/main/java/cloneproject/Instagram/domain/feed/dto/PostDto.java
  src/main/java/cloneproject/Instagram/domain/feed/dto/PostUploadRequest.java
  src/main/java/cloneproject/Instagram/domain/feed/repository/CommentRepository.java
  src/main/java/cloneproject/Instagram/domain/feed/repository/PostImageRepository.java
  src/main/java/cloneproject/Instagram/domain/feed/repository/querydsl/CommentRepositoryQuerydsl.java
  src/main/java/cloneproject/Instagram/domain/feed/repository/querydsl/CommentRepositoryQuerydslImpl.java
  src/main/java/cloneproject/Instagram/domain/feed/repository/querydsl/PostLikeRepositoryQuerydsl.java
  src/main/java/cloneproject/Instagram/domain/feed/repository/querydsl/PostLikeRepositoryQuerydslImpl.java
  src/main/java/cloneproject/Instagram/domain/feed/repository/querydsl/PostRepositoryQuerydsl.java
  src/main/java/cloneproject/Instagram/domain/feed/repository/querydsl/PostRepositoryQuerydslImpl.java
  src/main/java/cloneproject/Instagram/domain/feed/service/CommentService.java
  src/main/java/cloneproject/Instagram/domain/feed/service/PostService.java
  src/main/java/cloneproject/Instagram/domain/member/dto/LikeMemberDto.java
  src/main/java/cloneproject/Instagram/domain/member/service/MemberPostService.java
  src/main/java/cloneproject/Instagram/domain/member/service/MemberService.java
  src/main/java/cloneproject/Instagram/domain/story/service/MemberStoryService.java
  src/main/java/cloneproject/Instagram/global/error/ErrorCode.java
  src/test/resources/application-test.yml
  src/test/resources/application.yml
Labels: 💉bug, ✈enhancement, 💎refactor

#229 게시물 조회 관련 에러 해결
  src/main/java/cloneproject/Instagram/domain/feed/dto/PostDto.java
  src/main/java/cloneproject/Instagram/domain/feed/repository/querydsl/PostRepositoryQuerydslImpl.java
  src/main/java/cloneproject/Instagram/domain/feed/service/PostService.java
Labels: 💉bug
