Repository Instagram-Clone-Coding/Spring_instagram-clone, pull requests merged in 2022-08, with the labels that each got.

#188 로그인 없이 호출하는 API 추가
  src/main/java/cloneproject/Instagram/domain/member/controller/MemberAuthController.java
  src/main/java/cloneproject/Instagram/domain/member/controller/MemberController.java
  src/main/java/cloneproject/Instagram/domain/member/controller/MemberPostController.java
  src/main/java/cloneproject/Instagram/domain/member/repository/querydsl/MemberPostRepositoryQuerydsl.java
  src/main/java/cloneproject/Instagram/domain/member/repository/querydsl/MemberPostRepositoryQuerydslImpl.java
  src/main/java/cloneproject/Instagram/domain/member/service/MemberPostService.java
  src/main/java/cloneproject/Instagram/domain/member/service/MemberService.java
  src/main/java/cloneproject/Instagram/global/config/security/WebSecurityConfig.java
Labels: ✈enhancement

#189 (인증 x) 게시물 조회 API 추가
  src/main/java/cloneproject/Instagram/domain/feed/controller/PostController.java
  src/main/java/cloneproject/Instagram/domain/feed/dto/CommentDto.java
  src/main/java/cloneproject/Instagram/domain/feed/dto/PostResponse.java
  src/main/java/cloneproject/Instagram/domain/feed/repository/querydsl/CommentRepositoryQuerydsl.java
  src/main/java/cloneproject/Instagram/domain/feed/repository/querydsl/CommentRepositoryQuerydslImpl.java
  src/main/java/cloneproject/Instagram/domain/feed/repository/querydsl/PostRepositoryQuerydsl.java
  src/main/java/cloneproject/Instagram/domain/feed/repository/querydsl/PostRepositoryQuerydslImpl.java
  src/main/java/cloneproject/Instagram/domain/feed/service/PostService.java
Labels: ✈enhancement

#194 S3Uploader 리팩토링
  src/main/java/cloneproject/Instagram/domain/feed/service/PostImageService.java
  src/main/java/cloneproject/Instagram/domain/member/dto/EditProfileResponse.java
  src/main/java/cloneproject/Instagram/domain/member/dto/MenuMemberProfile.java
  src/main/java/cloneproject/Instagram/domain/member/entity/Member.java
  src/main/java/cloneproject/Instagram/domain/member/service/EmailCodeService.java
  src/main/java/cloneproject/Instagram/domain/member/service/MemberService.java
  src/main/java/cloneproject/Instagram/global/error/ErrorCode.java
  src/main/java/cloneproject/Instagram/global/error/exception/CantConvertFileException.java
  src/main/java/cloneproject/Instagram/global/error/exception/FileConvertFailException.java
  src/main/java/cloneproject/Instagram/global/result/ResultCode.java
  src/main/java/cloneproject/Instagram/infra/aws/S3Uploader.java
Labels: 💎refactor

#195 게시물/댓글/알림 조회 시 응답데이터 추가: 멘션/해시태그 목록
  src/main/java/cloneproject/Instagram/domain/alarm/dto/AlarmContentDto.java
  src/main/java/cloneproject/Instagram/domain/alarm/repository/querydsl/AlarmRepositoryQuerydslImpl.java
  src/main/java/cloneproject/Instagram/domain/alarm/service/AlarmService.java
  src/main/java/cloneproject/Instagram/domain/feed/controller/PostController.java
  src/main/java/cloneproject/Instagram/domain/feed/dto/CommentDto.java
  src/main/java/cloneproject/Instagram/domain/feed/dto/PostDto.java
  src/main/java/cloneproject/Instagram/domain/feed/dto/PostResponse.java
  src/main/java/cloneproject/Instagram/domain/feed/repository/querydsl/PostRepositoryQuerydsl.java
  src/main/java/cloneproject/Instagram/domain/feed/repository/querydsl/PostRepositoryQuerydslImpl.java
  src/main/java/cloneproject/Instagram/domain/feed/service/CommentService.java
  src/main/java/cloneproject/Instagram/domain/feed/service/PostService.java
  src/main/java/cloneproject/Instagram/domain/mention/repository/MentionRepository.java
  src/main/java/cloneproject/Instagram/domain/mention/service/MentionService.java
Labels: 💉bug, ✈enhancement

#198 story 도메인 테스트 코드 작성
  build.gradle
  src/main/java/cloneproject/Instagram/domain/search/dto/SearchHashtagDto.java
  src/main/java/cloneproject/Instagram/domain/search/dto/SearchMemberDto.java
  src/main/java/cloneproject/Instagram/domain/story/entity/Story.java
  src/main/java/cloneproject/Instagram/domain/story/entity/StoryVisitor.java
  src/main/java/cloneproject/Instagram/global/config/EmbeddedRedisConfig.java
  src/main/java/cloneproject/Instagram/global/config/JpaAuditingConfig.java
  src/main/java/cloneproject/Instagram/global/config/RedisConfig.java
  src/main/java/cloneproject/Instagram/global/config/security/CustomRequestMatcher.java
  src/main/java/cloneproject/Instagram/global/config/security/filter/ReissueAuthenticationFilter.java
  src/main/java/cloneproject/Instagram/global/config/security/provider/ResetPasswordCodeAuthenticationProvider.java
  src/main/java/cloneproject/Instagram/global/config/security/token/ReissueAuthenticationToken.java
  src/main/java/cloneproject/Instagram/global/config/security/token/ResetPasswordCodeAuthenticationToken.java
  src/test/java/cloneproject/Instagram/WithMockCustomUser.java
  src/test/java/cloneproject/Instagram/WithMockCustomUserSecurityContextFactory.java
  src/test/java/cloneproject/Instagram/controller/BlockControllerTest.java
  src/test/java/cloneproject/Instagram/controller/FollowControllerTest.java
  src/test/java/cloneproject/Instagram/controller/MemberAuthControllerTest.java
  src/test/java/cloneproject/Instagram/controller/MemberControllerTest.java
  src/test/java/cloneproject/Instagram/domain/story/repository/MemberStoryRedisRepositoryTest.java
  src/test/java/cloneproject/Instagram/repository/FollowRepositoryTest.java
  src/test/java/cloneproject/Instagram/repository/MemberPostRepositoryTest.java
  src/test/java/cloneproject/Instagram/repository/MemberRepositoryTest.java
  src/test/java/cloneproject/Instagram/service/BlockServiceTest.java
  src/test/java/cloneproject/Instagram/service/FollowServiceTest.java
  src/test/java/cloneproject/Instagram/service/MemberAuthServiceTest.java
  src/test/java/cloneproject/Instagram/service/MemberServiceTest.java
  src/test/java/cloneproject/Instagram/util/ImageUtils.java
  src/test/java/cloneproject/Instagram/util/domain/member/MemberUtils.java
  src/test/java/cloneproject/Instagram/util/domain/story/StoryUtils.java
  src/test/java/cloneproject/Instagram/util/domain/story/redis/MemberStoryUtils.java
  src/test/resources/application-test.yml
  src/test/resources/application.yml
Labels: 🔍test

#199 HibernateDialect 관련 버그 수정
  src/test/resources/application-test.yml
Labels: 💉bug

#201 FollowRepository내 RedisRepository 관련 의존성 제거
  src/main/java/cloneproject/Instagram/domain/follow/repository/querydsl/FollowRepositoryQuerydsl.java
  src/main/java/cloneproject/Instagram/domain/follow/repository/querydsl/FollowRepositoryQuerydslImpl.java
  src/main/java/cloneproject/Instagram/domain/follow/service/FollowService.java
Labels: 💎refactor

#202 MemberRepository 테스트 작성
  src/main/java/cloneproject/Instagram/domain/feed/dto/MemberPostDto.java
  src/main/java/cloneproject/Instagram/domain/member/repository/MemberRepository.java
  src/main/java/cloneproject/Instagram/domain/member/repository/querydsl/MemberPostRepositoryQuerydsl.java
  src/main/java/cloneproject/Instagram/domain/member/repository/querydsl/MemberPostRepositoryQuerydslImpl.java
  src/main/java/cloneproject/Instagram/domain/member/repository/querydsl/MemberRepositoryQuerydsl.java
  src/main/java/cloneproject/Instagram/domain/member/repository/querydsl/MemberRepositoryQuerydslImpl.java
  src/main/java/cloneproject/Instagram/global/util/PostUtil.java
  src/test/java/cloneproject/Instagram/domain/member/repository/MemberRepositoryTest.java
  src/test/java/cloneproject/Instagram/domain/member/repository/querydsl/MemberPostRepositoryQuerydslTest.java
  src/test/java/cloneproject/Instagram/domain/member/repository/querydsl/MemberRepositoryQuerydslTest.java
  src/test/java/cloneproject/Instagram/util/domain/feed/CommentUtils.java
  src/test/java/cloneproject/Instagram/util/domain/feed/PostImageUtils.java
  src/test/java/cloneproject/Instagram/util/domain/feed/PostLikeUtils.java
  src/test/java/cloneproject/Instagram/util/domain/feed/PostTagUtils.java
  src/test/java/cloneproject/Instagram/util/domain/feed/PostUtils.java
  src/test/java/cloneproject/Instagram/util/domain/member/FollowUtils.java
  src/test/java/cloneproject/Instagram/util/domain/member/MemberUtils.java
Labels: 🔍test

#203 PostController/PostService 리팩토링
  src/main/java/cloneproject/Instagram/domain/feed/controller/PostController.java
  src/main/java/cloneproject/Instagram/domain/feed/service/PostService.java
  src/main/java/cloneproject/Instagram/global/util/ConstantUtils.java
Labels: 💎refactor

#209 게시물 목록 조회(단건, 페이징) API 응답 데이터 추가 & 게시물 관련 쿼리 최적화
  src/main/java/cloneproject/Instagram/domain/alarm/service/AlarmService.java
  src/main/java/cloneproject/Instagram/domain/feed/dto/PostDto.java
  src/main/java/cloneproject/Instagram/domain/feed/dto/PostLikeCountDto.java
  src/main/java/cloneproject/Instagram/domain/feed/repository/querydsl/PostLikeRepositoryQuerydsl.java
  src/main/java/cloneproject/Instagram/domain/feed/repository/querydsl/PostLikeRepositoryQuerydslImpl.java
  src/main/java/cloneproject/Instagram/domain/feed/repository/querydsl/PostRepositoryQuerydslImpl.java
  src/main/java/cloneproject/Instagram/domain/feed/service/CommentService.java
  src/main/java/cloneproject/Instagram/domain/feed/service/PostService.java
  src/main/java/cloneproject/Instagram/domain/mention/service/MentionService.java
  src/main/java/cloneproject/Instagram/domain/story/service/StoryService.java
  src/main/java/cloneproject/Instagram/global/util/StringExtractUtil.java
Labels: ✈enhancement, 💎refactor

#208 MemberRepository 테스트 컨벤션 수정, Nested 적용
  src/main/java/cloneproject/Instagram/domain/feed/dto/MemberPostDto.java
  src/main/java/cloneproject/Instagram/domain/member/repository/querydsl/MemberPostRepositoryQuerydsl.java
  src/main/java/cloneproject/Instagram/domain/member/repository/querydsl/MemberPostRepositoryQuerydslImpl.java
  src/main/java/cloneproject/Instagram/domain/member/repository/querydsl/MemberRepositoryQuerydsl.java
  src/main/java/cloneproject/Instagram/domain/member/repository/querydsl/MemberRepositoryQuerydslImpl.java
  src/main/java/cloneproject/Instagram/domain/member/service/MemberPostService.java
  src/main/java/cloneproject/Instagram/domain/member/service/MemberService.java
  src/test/java/cloneproject/Instagram/domain/member/repository/MemberRepositoryTest.java
  src/test/java/cloneproject/Instagram/domain/member/repository/querydsl/MemberPostRepositoryQuerydslTest.java
  src/test/java/cloneproject/Instagram/domain/member/repository/querydsl/MemberRepositoryQuerydslTest.java
Labels: 🔍test
