Repository Instagram-Clone-Coding/Spring_instagram-clone, pull requests merged in 2022-07, with the labels that each got.

#170 FollowingMemberFollow 로직 수정
  src/main/java/cloneproject/Instagram/domain/follow/repository/querydsl/FollowRepositoryQuerydsl.java
  src/main/java/cloneproject/Instagram/domain/follow/repository/querydsl/FollowRepositoryQuerydslImpl.java
  src/main/java/cloneproject/Instagram/domain/hashtag/exception/HashtagPrefixMismatchException.java
  src/main/java/cloneproject/Instagram/domain/member/dto/MiniProfileResponse.java
  src/main/java/cloneproject/Instagram/domain/member/dto/UserProfileResponse.java
  src/main/java/cloneproject/Instagram/domain/member/repository/querydsl/MemberRepositoryQuerydslImpl.java
  src/main/java/cloneproject/Instagram/domain/member/service/MemberService.java
  src/main/java/cloneproject/Instagram/domain/search/dto/SearchMemberDto.java
  src/main/java/cloneproject/Instagram/domain/search/service/SearchService.java
  src/main/java/cloneproject/Instagram/global/error/ErrorCode.java
Labels: 💎refactor

#173 Member 관련 Swagger 컨벤션 적용
  src/main/java/cloneproject/Instagram/domain/feed/controller/CommentController.java
  src/main/java/cloneproject/Instagram/domain/feed/controller/PostController.java
  src/main/java/cloneproject/Instagram/domain/feed/repository/querydsl/PostLikeRepositoryQuerydsl.java
  src/main/java/cloneproject/Instagram/domain/feed/repository/querydsl/PostLikeRepositoryQuerydslImpl.java
  src/main/java/cloneproject/Instagram/domain/feed/service/CommentService.java
  src/main/java/cloneproject/Instagram/domain/feed/service/PostService.java
  src/main/java/cloneproject/Instagram/domain/member/controller/MemberAuthController.java
  src/main/java/cloneproject/Instagram/domain/member/controller/MemberController.java
  src/main/java/cloneproject/Instagram/domain/member/controller/MemberPostController.java
  src/main/java/cloneproject/Instagram/domain/member/dto/EditProfileRequest.java
  src/main/java/cloneproject/Instagram/domain/member/dto/JwtDto.java
  src/main/java/cloneproject/Instagram/domain/member/dto/JwtResponse.java
  src/main/java/cloneproject/Instagram/domain/member/dto/LikeMemberDto.java
  src/main/java/cloneproject/Instagram/domain/member/dto/LoginDevicesDto.java
  src/main/java/cloneproject/Instagram/domain/member/dto/LoginRequest.java
  src/main/java/cloneproject/Instagram/domain/member/dto/LoginWithCodeRequest.java
  src/main/java/cloneproject/Instagram/domain/member/dto/MemberDto.java
  src/main/java/cloneproject/Instagram/domain/member/dto/MenuMemberProfile.java
  src/main/java/cloneproject/Instagram/domain/member/dto/RegisterRequest.java
  src/main/java/cloneproject/Instagram/domain/member/dto/ResetPasswordRequest.java
  src/main/java/cloneproject/Instagram/domain/member/dto/SendConfirmationEmailRequest.java
  src/main/java/cloneproject/Instagram/domain/member/dto/UpdatePasswordRequest.java
  src/main/java/cloneproject/Instagram/domain/member/dto/UserProfileResponse.java
  src/main/java/cloneproject/Instagram/domain/member/exception/EmailNotConfirmedException.java
  src/main/java/cloneproject/Instagram/domain/member/repository/querydsl/MemberPostRepositoryQuerydsl.java
  src/main/java/cloneproject/Instagram/domain/member/repository/querydsl/MemberPostRepositoryQuerydslImpl.java
  src/main/java/cloneproject/Instagram/domain/member/repository/querydsl/MemberRepositoryQuerydsl.java
  src/main/java/cloneproject/Instagram/domain/member/repository/querydsl/MemberRepositoryQuerydslImpl.java
  src/main/java/cloneproject/Instagram/domain/member/service/EmailCodeService.java
  src/main/java/cloneproject/Instagram/domain/member/service/MemberAuthService.java
  src/main/java/cloneproject/Instagram/domain/member/service/MemberPostService.java
  src/main/java/cloneproject/Instagram/domain/member/service/MemberService.java
  src/main/java/cloneproject/Instagram/domain/member/service/RefreshTokenService.java
  src/main/java/cloneproject/Instagram/global/config/security/WebSecurityConfig.java
  src/main/java/cloneproject/Instagram/global/config/security/filter/ReissueAuthenticationFilter.java
  src/main/java/cloneproject/Instagram/global/error/ErrorCode.java
  src/main/java/cloneproject/Instagram/global/result/ResultCode.java
  src/test/java/cloneproject/Instagram/repository/MemberRepositoryTest.java
  src/test/java/cloneproject/Instagram/service/MemberServiceTest.java
Labels: 💎refactor

#175 카카오 지도 API 추가
  src/main/java/cloneproject/Instagram/domain/feed/repository/querydsl/PostLikeRepositoryQuerydslImpl.java
  src/main/java/cloneproject/Instagram/domain/member/controller/MemberAuthController.java
  src/main/java/cloneproject/Instagram/domain/member/controller/MemberController.java
  src/main/java/cloneproject/Instagram/domain/member/dto/LoginDevicesDto.java
  src/main/java/cloneproject/Instagram/domain/member/entity/redis/RefreshToken.java
  src/main/java/cloneproject/Instagram/domain/member/service/MemberAuthService.java
  src/main/java/cloneproject/Instagram/domain/member/service/RefreshTokenService.java
  src/main/java/cloneproject/Instagram/global/config/security/handler/CustomAuthenticationSuccessHandler.java
  src/main/java/cloneproject/Instagram/global/error/ErrorCode.java
  src/main/java/cloneproject/Instagram/infra/geoip/GeoIPLocationService.java
  src/main/java/cloneproject/Instagram/infra/kakao/KakaoMap.java
  src/main/java/cloneproject/Instagram/infra/kakao/dto/KakaoSearchResponse.java
  src/main/java/cloneproject/Instagram/infra/kakao/exception/KakaoMapApiFailException.java
  src/main/java/cloneproject/Instagram/infra/location/LocationService.java
  src/main/java/cloneproject/Instagram/infra/location/dto/Location.java
Labels: ✈enhancement, 💎refactor

#179 검색 자동완성 추가, 카카오 맵 API 수정
  src/main/java/cloneproject/Instagram/domain/hashtag/repository/HashtagRepository.java
  src/main/java/cloneproject/Instagram/domain/member/repository/MemberRepository.java
  src/main/java/cloneproject/Instagram/domain/search/controller/SearchController.java
  src/main/java/cloneproject/Instagram/domain/search/repository/querydsl/SearchRepositoryQuerydsl.java
  src/main/java/cloneproject/Instagram/domain/search/repository/querydsl/SearchRepositoryQuerydslImpl.java
  src/main/java/cloneproject/Instagram/domain/search/service/SearchService.java
  src/main/java/cloneproject/Instagram/global/result/ResultCode.java
  src/main/java/cloneproject/Instagram/infra/kakao/KakaoMap.java
  src/main/java/cloneproject/Instagram/infra/kakao/dto/KakaoSearchResponse.java
Labels: ✈enhancement, 💎refactor

#181 해시태그 도메인 컨벤션 적용
  src/main/java/cloneproject/Instagram/domain/hashtag/controller/HashtagController.java
  src/main/java/cloneproject/Instagram/domain/hashtag/dto/HashtagDTO.java
  src/main/java/cloneproject/Instagram/domain/hashtag/entity/Hashtag.java
  src/main/java/cloneproject/Instagram/domain/hashtag/entity/HashtagPost.java
  src/main/java/cloneproject/Instagram/domain/hashtag/exception/HashtagNotFoundException.java
  src/main/java/cloneproject/Instagram/domain/hashtag/repository/HashtagPostRepository.java
  src/main/java/cloneproject/Instagram/domain/hashtag/repository/HashtagRepository.java
  src/main/java/cloneproject/Instagram/domain/hashtag/repository/jdbc/HashtagPostRepositoryJdbc.java
  src/main/java/cloneproject/Instagram/domain/hashtag/repository/jdbc/HashtagPostRepositoryJdbcImpl.java
  src/main/java/cloneproject/Instagram/domain/hashtag/service/HashtagService.java
  src/main/java/cloneproject/Instagram/domain/search/controller/SearchController.java
  src/main/java/cloneproject/Instagram/domain/search/service/SearchService.java
  src/main/java/cloneproject/Instagram/global/error/ErrorCode.java
  src/main/java/cloneproject/Instagram/global/result/ResultCode.java
Labels: 💎refactor

#177 게시물 업로드 옵션 추가
  src/main/java/cloneproject/Instagram/domain/feed/controller/CommentController.java
  src/main/java/cloneproject/Instagram/domain/feed/controller/PostController.java
  src/main/java/cloneproject/Instagram/domain/feed/dto/CommentDto.java
  src/main/java/cloneproject/Instagram/domain/feed/dto/CommentUploadRequest.java
  src/main/java/cloneproject/Instagram/domain/feed/dto/CommentUploadResponse.java
  src/main/java/cloneproject/Instagram/domain/feed/dto/MemberPostDto.java
  src/main/java/cloneproject/Instagram/domain/feed/dto/MiniProfilePostDto.java
  src/main/java/cloneproject/Instagram/domain/feed/dto/PostDto.java
  src/main/java/cloneproject/Instagram/domain/feed/dto/PostImageDto.java
  src/main/java/cloneproject/Instagram/domain/feed/dto/PostImageTagRequest.java
  src/main/java/cloneproject/Instagram/domain/feed/dto/PostLikeDto.java
  src/main/java/cloneproject/Instagram/domain/feed/dto/PostResponse.java
  src/main/java/cloneproject/Instagram/domain/feed/dto/PostTagDto.java
  src/main/java/cloneproject/Instagram/domain/feed/dto/PostUploadRequest.java
  src/main/java/cloneproject/Instagram/domain/feed/entity/Bookmark.java
  src/main/java/cloneproject/Instagram/domain/feed/entity/Comment.java
  src/main/java/cloneproject/Instagram/domain/feed/entity/CommentLike.java
  src/main/java/cloneproject/Instagram/domain/feed/entity/Post.java
  src/main/java/cloneproject/Instagram/domain/feed/entity/PostImage.java
  src/main/java/cloneproject/Instagram/domain/feed/entity/PostLike.java
  src/main/java/cloneproject/Instagram/domain/feed/entity/PostTag.java
  src/main/java/cloneproject/Instagram/domain/feed/entity/RecentComment.java
  src/main/java/cloneproject/Instagram/domain/feed/repository/BookmarkRepository.java
  src/main/java/cloneproject/Instagram/domain/feed/repository/CommentLikeRepository.java
  src/main/java/cloneproject/Instagram/domain/feed/repository/CommentRepository.java
  src/main/java/cloneproject/Instagram/domain/feed/repository/PostImageRepository.java
  src/main/java/cloneproject/Instagram/domain/feed/repository/PostLikeRepository.java
  src/main/java/cloneproject/Instagram/domain/feed/repository/PostRepository.java
  src/main/java/cloneproject/Instagram/domain/feed/repository/PostTagRepository.java
  src/main/java/cloneproject/Instagram/domain/feed/repository/RecentCommentRepository.java
  src/main/java/cloneproject/Instagram/domain/feed/repository/jdbc/PostImageRepositoryJdbc.java
  src/main/java/cloneproject/Instagram/domain/feed/repository/jdbc/PostImageRepositoryJdbcImpl.java
  src/main/java/cloneproject/Instagram/domain/feed/repository/jdbc/PostTagRepositoryJdbc.java
  src/main/java/cloneproject/Instagram/domain/feed/repository/jdbc/PostTagRepositoryJdbcImpl.java
  src/main/java/cloneproject/Instagram/domain/feed/repository/querydsl/CommentRepositoryQuerydslImpl.java
  src/main/java/cloneproject/Instagram/domain/feed/repository/querydsl/PostLikeRepositoryQuerydsl.java
  src/main/java/cloneproject/Instagram/domain/feed/repository/querydsl/PostLikeRepositoryQuerydslImpl.java
  src/main/java/cloneproject/Instagram/domain/feed/repository/querydsl/PostRepositoryQuerydsl.java
  src/main/java/cloneproject/Instagram/domain/feed/repository/querydsl/PostRepositoryQuerydslImpl.java
  src/main/java/cloneproject/Instagram/domain/feed/service/CommentLikeService.java
  src/main/java/cloneproject/Instagram/domain/feed/service/CommentService.java
  src/main/java/cloneproject/Instagram/domain/feed/service/PostImageService.java
  src/main/java/cloneproject/Instagram/domain/feed/service/PostLikeService.java
  src/main/java/cloneproject/Instagram/domain/feed/service/PostService.java
  src/main/java/cloneproject/Instagram/domain/feed/service/PostTagService.java
  src/main/java/cloneproject/Instagram/domain/feed/service/RecentCommentService.java
  src/main/java/cloneproject/Instagram/domain/feed/vo/Tag.java
  src/main/java/cloneproject/Instagram/domain/follow/repository/FollowRepository.java
  src/main/java/cloneproject/Instagram/domain/follow/service/FollowService.java
  src/main/java/cloneproject/Instagram/domain/member/controller/MemberPostController.java
  src/main/java/cloneproject/Instagram/domain/member/repository/querydsl/MemberPostRepositoryQuerydsl.java
  src/main/java/cloneproject/Instagram/domain/member/repository/querydsl/MemberPostRepositoryQuerydslImpl.java
  src/main/java/cloneproject/Instagram/domain/member/service/MemberPostService.java
  src/main/java/cloneproject/Instagram/domain/mention/repository/MentionRepository.java
  src/main/java/cloneproject/Instagram/global/error/ErrorResponse.java
  src/main/java/cloneproject/Instagram/global/util/StringExtractUtil.java
Labels: ✈enhancement
