Repository Instagram-Clone-Coding/Spring_instagram-clone, pull requests merged in 2022-03, with the labels that each got.

#121 MemberPostRepositoryTest 에러 수정
  src/test/java/cloneproject/Instagram/repository/MemberPostRepositoryTest.java
Labels: 💎refactor, 🔍test

#123 해시태그 API 추가
  src/main/java/cloneproject/Instagram/config/WebSecurityConfig.java
  src/main/java/cloneproject/Instagram/controller/HashtagController.java
  src/main/java/cloneproject/Instagram/controller/PostController.java
  src/main/java/cloneproject/Instagram/dto/hashtag/HashtagDTO.java
  src/main/java/cloneproject/Instagram/dto/result/ResultCode.java
  src/main/java/cloneproject/Instagram/entity/hashtag/Hashtag.java
  src/main/java/cloneproject/Instagram/entity/post/HashtagPost.java
  src/main/java/cloneproject/Instagram/repository/HashTagRepositoryQuerydsl.java
  src/main/java/cloneproject/Instagram/repository/HashTagRepositoryQuerydslImpl.java
  src/main/java/cloneproject/Instagram/repository/HashtagPostRepository.java
  src/main/java/cloneproject/Instagram/repository/HashtagPostRepositoryJdbc.java
  src/main/java/cloneproject/Instagram/repository/HashtagPostRepositoryJdbcImpl.java
  src/main/java/cloneproject/Instagram/repository/HashtagRepository.java
  src/main/java/cloneproject/Instagram/repository/HashtagRepositoryJdbc.java
  src/main/java/cloneproject/Instagram/repository/post/PostRepositoryQuerydsl.java
  src/main/java/cloneproject/Instagram/repository/post/PostRepositoryQuerydslImpl.java
  src/main/java/cloneproject/Instagram/service/HashtagService.java
  src/main/java/cloneproject/Instagram/service/PostService.java
Labels: ✈enhancement

#125 동일 트랜잭션에서 DiscriminatorValue을 가져오지 못하는 문제 해결
  src/main/java/cloneproject/Instagram/entity/chat/Message.java
  src/main/java/cloneproject/Instagram/service/ChatService.java
  src/main/java/cloneproject/Instagram/service/PostService.java
Labels: 💉bug

#126 Test: Follow, Block Controller 테스트 작성
  src/test/java/cloneproject/Instagram/controller/BlockControllerTest.java
  src/test/java/cloneproject/Instagram/controller/FollowControllerTest.java
  src/test/java/cloneproject/Instagram/controller/MemberAuthControllerTest.java
Labels: 🔍test

#129 채팅 API content-type 오류 및 이미지 전송 API http 통신으로 변경
  src/main/java/cloneproject/Instagram/controller/ChatController.java
  src/main/java/cloneproject/Instagram/dto/chat/MessageSimpleRequest.java
  src/main/java/cloneproject/Instagram/dto/result/ResultCode.java
  src/main/java/cloneproject/Instagram/service/ChatService.java
Labels: 💉bug, ✈enhancement

#133 메시지 삭제 API 로직 오류 해결
  src/main/java/cloneproject/Instagram/repository/chat/JoinRoomRepository.java
  src/main/java/cloneproject/Instagram/repository/chat/MessageRepository.java
  src/main/java/cloneproject/Instagram/service/ChatService.java
Labels: 💉bug

#131 회원가입 인증코드 이메일 HTML 적용, 멤버 인증 테스트 작성
  src/main/java/cloneproject/Instagram/controller/MemberAuthController.java
  src/main/java/cloneproject/Instagram/dto/error/ErrorCode.java
  src/main/java/cloneproject/Instagram/exception/CantSendEmailException.java
  src/main/java/cloneproject/Instagram/service/EmailCodeService.java
  src/main/java/cloneproject/Instagram/service/EmailService.java
  src/main/resources/confirmEmailUI.html
  src/test/java/cloneproject/Instagram/controller/MemberAuthControllerTest.java
  src/test/java/cloneproject/Instagram/service/MemberAuthServiceTest.java
Labels: 💎refactor, 🔍test

#137 Refactor: 로그아웃 추가, 비밀번호 재설정 API 일부 수정
  src/main/java/cloneproject/Instagram/controller/MemberAuthController.java
  src/main/java/cloneproject/Instagram/dto/result/ResultCode.java
  src/main/java/cloneproject/Instagram/entity/member/Member.java
  src/main/java/cloneproject/Instagram/service/MemberAuthService.java
  src/main/resources/confirmEmailUI.html
Labels: 💎refactor

#138 다중 기기 로그인 구현
  .gitignore
  build.gradle
  src/main/java/cloneproject/Instagram/config/GeoIPConfig.java
  src/main/java/cloneproject/Instagram/config/WebSecurityConfig.java
  src/main/java/cloneproject/Instagram/controller/MemberAuthController.java
  src/main/java/cloneproject/Instagram/dto/member/LoginWithCodeRequest.java
  src/main/java/cloneproject/Instagram/dto/member/LoginedDevicesDTO.java
  src/main/java/cloneproject/Instagram/dto/result/ResultCode.java
  src/main/java/cloneproject/Instagram/entity/member/Member.java
  src/main/java/cloneproject/Instagram/entity/redis/RefreshToken.java
  src/main/java/cloneproject/Instagram/repository/RefreshTokenRedisRepository.java
  src/main/java/cloneproject/Instagram/repository/RefreshTokenRepositoryQuerydsl.java
  src/main/java/cloneproject/Instagram/service/EmailCodeService.java
  src/main/java/cloneproject/Instagram/service/GeoIPLocationService.java
  src/main/java/cloneproject/Instagram/service/MemberAuthService.java
  src/main/java/cloneproject/Instagram/service/RefreshTokenService.java
  src/main/java/cloneproject/Instagram/vo/GeoIP.java
  src/main/java/cloneproject/Instagram/vo/RefreshToken.java
Labels: 💎refactor

#140 스토리 업로드 API 추가 및 스토리 업로드 여부 응답 데이터에 추가 등
  src/main/java/cloneproject/Instagram/controller/ChatController.java
  src/main/java/cloneproject/Instagram/controller/PostController.java
  src/main/java/cloneproject/Instagram/controller/StoryController.java
  src/main/java/cloneproject/Instagram/dto/alarm/AlarmContentDTO.java
  src/main/java/cloneproject/Instagram/dto/alarm/AlarmDTO.java
  src/main/java/cloneproject/Instagram/dto/alarm/AlarmFollowDTO.java
  src/main/java/cloneproject/Instagram/dto/chat/MessageDTO.java
  src/main/java/cloneproject/Instagram/dto/chat/MessageSimpleDTO.java
  src/main/java/cloneproject/Instagram/dto/comment/CommentDTO.java
  src/main/java/cloneproject/Instagram/dto/error/ErrorCode.java
  src/main/java/cloneproject/Instagram/dto/member/FollowerDTO.java
  src/main/java/cloneproject/Instagram/dto/member/LikeMembersDTO.java
  src/main/java/cloneproject/Instagram/dto/member/MemberDTO.java
  src/main/java/cloneproject/Instagram/dto/member/MenuMemberDTO.java
  src/main/java/cloneproject/Instagram/dto/member/MiniProfileResponse.java
  src/main/java/cloneproject/Instagram/dto/member/SearchedMemberDTO.java
  src/main/java/cloneproject/Instagram/dto/member/UserProfileResponse.java
  src/main/java/cloneproject/Instagram/dto/post/PostDTO.java
  src/main/java/cloneproject/Instagram/dto/result/ResultCode.java
  src/main/java/cloneproject/Instagram/dto/story/StoryContentRequest.java
  src/main/java/cloneproject/Instagram/dto/story/StoryUploadRequest.java
  src/main/java/cloneproject/Instagram/entity/chat/MessageStory.java
  src/main/java/cloneproject/Instagram/entity/member/MemberStory.java
  src/main/java/cloneproject/Instagram/entity/story/Story.java
  src/main/java/cloneproject/Instagram/entity/story/StoryHashtag.java
  src/main/java/cloneproject/Instagram/entity/story/StoryTag.java
  src/main/java/cloneproject/Instagram/repository/AlarmRepositoryQuerydslImpl.java
  src/main/java/cloneproject/Instagram/repository/FollowRepositoryQuerydsl.java
  src/main/java/cloneproject/Instagram/repository/FollowRepositoryQuerydslImpl.java
  src/main/java/cloneproject/Instagram/repository/MemberRepositoryQuerydslImpl.java
  src/main/java/cloneproject/Instagram/repository/PostLikeRepositoryQuerydslImpl.java
  src/main/java/cloneproject/Instagram/repository/chat/MessageRepositoryQuerydslImpl.java
  src/main/java/cloneproject/Instagram/repository/post/CommentRepositoryQuerydslImpl.java
  src/main/java/cloneproject/Instagram/repository/post/PostRepositoryQuerydslImpl.java
  src/main/java/cloneproject/Instagram/repository/story/MemberStoryRedisRepository.java
  src/main/java/cloneproject/Instagram/repository/story/MessageStoryRepository.java
  src/main/java/cloneproject/Instagram/repository/story/StoryRepository.java
  src/main/java/cloneproject/Instagram/service/FollowService.java
  src/main/java/cloneproject/Instagram/service/StoryService.java
  src/test/java/cloneproject/Instagram/repository/FollowRepositoryTest.java
Labels: ✈enhancement

#145 Feature/hashtag follow
  src/main/java/cloneproject/Instagram/controller/HashtagController.java
  src/main/java/cloneproject/Instagram/controller/MemberController.java
  src/main/java/cloneproject/Instagram/controller/SearchController.java
  src/main/java/cloneproject/Instagram/dto/error/ErrorCode.java
  src/main/java/cloneproject/Instagram/dto/hashtag/HashtagDTO.java
  src/main/java/cloneproject/Instagram/dto/member/SearchedMemberDTO.java
  src/main/java/cloneproject/Instagram/dto/result/ResultCode.java
  src/main/java/cloneproject/Instagram/dto/search/SearchDTO.java
  src/main/java/cloneproject/Instagram/dto/search/SearchHashtagDTO.java
  src/main/java/cloneproject/Instagram/dto/search/SearchMemberDTO.java
  src/main/java/cloneproject/Instagram/entity/member/HashtagFollow.java
  src/main/java/cloneproject/Instagram/entity/search/Search.java
  src/main/java/cloneproject/Instagram/entity/search/SearchHashtag.java
  src/main/java/cloneproject/Instagram/entity/search/SearchMember.java
  src/main/java/cloneproject/Instagram/exception/CantFollowHashtagException.java
  src/main/java/cloneproject/Instagram/exception/CantUnfollowHashtagException.java
  src/main/java/cloneproject/Instagram/exception/HashtagNotFoundException.java
  src/main/java/cloneproject/Instagram/repository/HashTagRepositoryQuerydsl.java
  src/main/java/cloneproject/Instagram/repository/HashTagRepositoryQuerydslImpl.java
  src/main/java/cloneproject/Instagram/repository/HashtagFollowRepository.java
  src/main/java/cloneproject/Instagram/repository/HashtagRepository.java
  src/main/java/cloneproject/Instagram/repository/MemberRepositoryQuerydsl.java
  src/main/java/cloneproject/Instagram/repository/MemberRepositoryQuerydslImpl.java
  src/main/java/cloneproject/Instagram/repository/search/SearchHashtagRepository.java
  src/main/java/cloneproject/Instagram/repository/search/SearchMemberRepository.java
  src/main/java/cloneproject/Instagram/repository/search/SearchRepository.java
  src/main/java/cloneproject/Instagram/repository/search/SearchRepositoryQuerydsl.java
  src/main/java/cloneproject/Instagram/repository/search/SearchRepositoryQuerydslImpl.java
  src/main/java/cloneproject/Instagram/service/HashtagService.java
  src/main/java/cloneproject/Instagram/service/MemberAuthService.java
  src/main/java/cloneproject/Instagram/service/MemberService.java
  src/main/java/cloneproject/Instagram/service/PostService.java
  src/main/java/cloneproject/Instagram/service/SearchService.java
Labels: ✈enhancement

#149 회원 스토리 조회 API 추가
  src/main/java/cloneproject/Instagram/controller/StoryController.java
  src/main/java/cloneproject/Instagram/dto/error/ErrorCode.java
  src/main/java/cloneproject/Instagram/dto/result/ResultCode.java
  src/main/java/cloneproject/Instagram/dto/story/MemberStoryDto.java
  src/main/java/cloneproject/Instagram/dto/story/StoryDto.java
  src/main/java/cloneproject/Instagram/entity/member/MemberStory.java
  src/main/java/cloneproject/Instagram/entity/story/StoryVisitor.java
  src/main/java/cloneproject/Instagram/exception/MemberStoryNotFoundException.java
  src/main/java/cloneproject/Instagram/repository/AlarmRepositoryQuerydslImpl.java
  src/main/java/cloneproject/Instagram/repository/FollowRepositoryQuerydslImpl.java
  src/main/java/cloneproject/Instagram/repository/MemberRepositoryQuerydslImpl.java
  src/main/java/cloneproject/Instagram/repository/PostLikeRepositoryQuerydslImpl.java
  src/main/java/cloneproject/Instagram/repository/post/CommentRepositoryQuerydslImpl.java
  src/main/java/cloneproject/Instagram/repository/post/PostRepositoryQuerydslImpl.java
  src/main/java/cloneproject/Instagram/repository/story/MemberStoryRedisRepository.java
  src/main/java/cloneproject/Instagram/repository/story/StoryVisitorRepository.java
  src/main/java/cloneproject/Instagram/service/StoryService.java
  src/main/java/cloneproject/Instagram/util/AuthUtil.java
Labels: ✈enhancement

#154 팔로워 삭제 API 구현, 이메일 서비스 수정 사항
  src/main/java/cloneproject/Instagram/domain/follow/controller/FollowController.java
  src/main/java/cloneproject/Instagram/domain/follow/exception/CantDeleteFollowerException.java
  src/main/java/cloneproject/Instagram/domain/follow/service/FollowService.java
  src/main/java/cloneproject/Instagram/domain/member/service/EmailCodeService.java
  src/main/java/cloneproject/Instagram/domain/member/service/MemberAuthService.java
  src/main/java/cloneproject/Instagram/global/error/ErrorCode.java
  src/main/java/cloneproject/Instagram/global/result/ResultCode.java
  src/main/resources/resetPasswordEmailUI.html
Labels: ✈enhancement, 💎refactor

#155 Fix: 유저 프로필 수정 조회 API 수정
  src/main/java/cloneproject/Instagram/domain/member/service/MemberService.java
Labels: 💉bug
